spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}

server:
  port: ${PORT:8080}

commerceai:
  frontend-url: ${FRONTEND_URL:}
